### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by peng-huang-ch** [peng-huang-ch/blockchain-notes#3]
[signature](https://github.com/ethereumjs/ethereumjs-monorepo/blob/cff15170235cf4bbe6e12e45a829fd7652416a9f/packages/tx/src/legacyTransaction.ts#L172)

**Comment by peng-huang-cc** [comment]
[signature](https://github.com/ethereumjs/ethereumjs-monorepo/blob/cff15170235cf4bbe6e12e45a829fd7652416a9f/packages/tx/src/legacyTransaction.ts#L172)

**Comment by peng-huang-cc** [comment]
[以太坊智能合约实现批量转账(空投)可转代币或者以太币](https://blog.csdn.net/zgf1991/article/details/90756619)

**Comment by peng-huang-cc** [comment]
`TODO`
- [ ] EIP-1559
