### ISSUE TITLE
Multi-party computation (MPC)

### ISSUE THREAD

**Issue by peng-huang-ch** [peng-huang-ch/blockchain-notes#88]
## Awesome
- [awesome-mpc](https://github.com/rdragos/awesome-mpc)

## Research
- [What is a multi-party computation (MPC) wallet?](https://www.alchemy.com/overviews/mpc-wallet) - By [Shray Jain](https://www.alchemy.com/author/shray-jain), [alchemy](www.alchemy.com)
- [What are MPC Wallets (Secure Multi-Party Computation) ](https://safeheron.com/blog/what-are-mpc-wallets/) - By [Safeheron Team](https://safeheron.com)
- [Exploring the Four Levels of MPC](https://blog.web3auth.io/mpc-embedded-wallet-comparison/) - By [Matthias Geihs](https://blog.web3auth.io/author/matthias/) and others, [web3auth](https://web3auth.io/)
- [What are multi-party computation (MPC) wallets?](https://cointelegraph.com/learn/mpc-wallets) - By [Tayyub Yaqoob](https://cointelegraph.com/authors/tayyub-yaqoob), [cointelegraph](https://cointelegraph.com)
- [Threshold Signatures Explained](https://academy.binance.com/en/articles/threshold-signatures-explained) - By [Omer Shlomovits](https://twitter.com/OmerShlomovits), [ZenGo](https://zengo.com/).
- [What Are Multi-Party Computation (MPC) Wallets?](https://academy.binance.com/en/articles/what-are-multi-party-computation-mpc-wallets) - By [binance](https://academy.binance.com/)

**Comment by nivek-ph** [comment]
## Awesome team/libs

- [ZenGo-X](https://github.com/ZenGo-X) - ZengoX is a research group composed of researchers from academia and industry.
  - [multi-party-ecdsa](https://github.com/ZenGo-X/multi-party-ecdsa) - A Rust implementation of {t,n}-threshold ECDSA (elliptic curve digital signature algorithm).

- [Bnb](https://github.com/bnb-chain) - BNB Smart Chain, BNB Beacon Chain
  - [tss-lib](https://github.com/bnb-chain/tss-lib) - An implementation of multi-party {t,n}-threshold ECDSA (Elliptic Curve Digital Signature Algorithm) based on Gennaro and Goldfeder CCS 2018 [1](https://img.shields.io/badge/license-MIT-blue.svg) and EdDSA (Edwards-curve Digital Signature Algorithm) following a similar approach.
  - [tss](https://github.com/bnb-chain/tss) - Cli and transportation wrapper of [tss-lib](https://github.com/binance-chain/tss-lib)
- [BitGo](https://github.com/BitGo) - BitGo provides regulated custody, financial services, and core infrastructure for investors and builders alike.
  - [sdk-lib-mpc](https://github.com/BitGo/BitGoJS/tree/master/modules/sdk-lib-mpc) - BitGoJS mpc sdk
- [thorchain](https://thorchain.org/) - Decentralized Cross-Chain Infrastructure
  - [go-tss](https://gitlab.com/thorchain/tss/go-tss)
- [incubator-milagro-MPC](https://github.com/apache/incubator-milagro-MPC) - AMCL - Apache Milagro Crypto Multi-Party Computation
- [bitgo-tss](https://github.com/BitGo/BitGoJS/tree/master/modules/sdk-core/src/bitgo/tss)
 - [mpcium](https://github.com/fystack/mpcium)

**Comment by peng-huang-ch** [comment]
[glossary](https://web3auth.io/docs/infrastructure/glossary)
- Shamir Secret Sharing (SSS)
- Verifiable Secret Sharing (VSS)
- Threshold Signature Schemes (TSS)
- Distributed Key Generation (DKG)

**Comment by nivek-ph** [comment]
# 🧩 MPC / TSS 开源库汇总（2025 年 11 月版）

> 本文整理了当前活跃的多方安全计算（MPC）与门限签名（TSS）开源实现，  

---

## 🌐 一、主流 / 生产级实现

| 名称                               | 语言 | 支持算法                             | 链接                                                                                 | 简介                                                            |
| ---------------------------------- | ---- | ------------------------------------ | ------------------------------------------------------------------------------------ | --------------------------------------------------------------- |
| **FROST (by Zcash Foundation)**    | Rust | Schnorr Threshold (Ed25519 / BIP340) | [github.com/ZcashFoundation/frost](https://github.com/ZcashFoundation/frost)         | 高效两轮 Schnorr 门限签名协议；Zcash 官方维护，部分审计完成。   |
| **multi-party-ecdsa (by ZenGo-X)** | Rust | ECDSA (GG18 / GG20)                  | [github.com/ZenGo-X/multi-party-ecdsa](https://github.com/ZenGo-X/multi-party-ecdsa) | 早期学术实现，广泛用于研究和衍生库。                            |
| **CGGMP21-Rust (by Lockness)**     | Rust | ECDSA (CG-GMP21 协议)                | [github.com/LFDT-Lockness/cggmp21](https://github.com/LFDT-Lockness/cggmp21)         | 现代高安全 ECDSA 协议实现，适合生产环境。                       |
| **tss-lib (by BNB Chain)**         | Go   | ECDSA / EdDSA                        | [github.com/bnb-chain/tss-lib](https://github.com/bnb-chain/tss-lib)                 | 最广泛使用的 Go 门限签名库，支持 GG18 / GG20 协议及密钥重分配。 |
| **multi-party-sig (by TaurusHQ)** | Go | ECDSA (GG20 / CMP) | [github.com/taurushq-io/multi-party-sig](https://github.com/taurushq-io/multi-party-sig) | 瑞士 Taurus HQ 团队维护的现代 TSS 实现，基于 GG20 / CMP 协议，性能优秀，生产可用。 |
| **threshold-lib (by OKX)**         | Go   | ECDSA / Ed25519                      | [github.com/okx/threshold-lib](https://github.com/okx/threshold-lib)                 | OKX 自研库，用于托管钱包 / 资产管理场景。                       |

---

## 🏢 二、企业 / 实践导向库

| 名称                              | 语言     | 算法                             | 链接                                                                                         | 简介                                         |
| --------------------------------- | -------- | -------------------------------- | -------------------------------------------------------------------------------------------- | -------------------------------------------- |
| **IBM TSS**                       | Go       | ECDSA / BLS / PS                 | [github.com/IBM/TSS](https://github.com/IBM/TSS)                                             | IBM 通用门限签名框架，含广播与成员发现模块。 |
| **coinbase/cb-mpc**               | Go + C++ | ECDSA MPC                        | [github.com/coinbase/cb-mpc](https://github.com/coinbase/cb-mpc)                             | Coinbase 用于资产托管的多方计算库。          |
| **getamis/alice (HTSS)**          | Go       | Hierarchical Threshold Signature | [github.com/getamis/alice](https://github.com/getamis/alice)                                 | 支持多层级 HTSS 结构，适合权限分层签名系统。 |
| **luxfi/threshold**               | Go       | ECDSA / FROST / PQC              | [github.com/luxfi/threshold](https://github.com/luxfi/threshold)                             | 通用多链门限签名框架，覆盖 20+ 链。          |
| **safeheron/multi-party-sig-cpp** | C++      | GG18 / GG20 / CMP                | [github.com/Safeheron/multi-party-sig-cpp](https://github.com/Safeheron/multi-party-sig-cpp) | 高性能 C++ 实现，适合嵌入式或跨平台部署。    |

---

## 🧪 三、研究 / 实验性实现

| 名称                                   | 语言              | 支持算法                          | 链接                                                                                                 | 简介                                                                                       |
| -------------------------------------- | ----------------- | --------------------------------- | ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| **multi-party-eddsa (by ZenGo-X)**     | Rust              | EdDSA (Ed25519)                   | [github.com/ZenGo-X/multi-party-eddsa](https://github.com/ZenGo-X/multi-party-eddsa)                 | ZenGo 团队的门限 EdDSA 实现，基于 FROST 思想，支持 Ed25519；常用于验证多方签名协议正确性。 |
| **blind-threshold-bls-wasm (by Celo)** | TypeScript / WASM | BLS12-377 Blind Threshold         | [github.com/celo-org/blind-threshold-bls-wasm](https://github.com/celo-org/blind-threshold-bls-wasm) | 可在浏览器端运行的 BLS 盲门限签名实现。                                                    |
| **proactive-refresh**                  | Go                | BLS + Proactive Refresh           | [github.com/lyronctk/proactive-refresh](https://github.com/lyronctk/proactive-refresh)               | 实验性 “主动刷新” 机制，提高长期密钥安全。                                                 |
| **protect**                            | Java              | Secret Sharing / Threshold Crypto | [github.com/jasonkresch/protect](https://github.com/jasonkresch/protect)                             | 提供密钥分片、刷新、恢复的教学平台。                                                       |
| **ing-bank/threshold-signatures**      | Rust              | ECDSA (GG18)                      | [github.com/ing-bank/threshold-signatures](https://github.com/ing-bank/threshold-signatures)         | 荷兰 ING 银行研究项目；已归档。                                                            |
| **tinysig (by Nillion)**               | Python            | ECDSA (教学版)                    | [github.com/NillionNetwork/tinysig](https://github.com/NillionNetwork/tinysig)                       | 轻量教学实现，展示 ECDSA 门限签名流程。                                                    |
| **py-ggmpc**                           | Python            | ECDSA / EdDSA                     | [github.com/johnoliverdriscoll/py-ggmpc](https://github.com/johnoliverdriscoll/py-ggmpc)             | 学术实验用 MPC/TSS 库。                                                                    |
| **secp256k1-frost (by Bank of Italy)** | C / C++           | Schnorr (FROST)                   | [github.com/bancaditalia/secp256k1-frost](https://github.com/bancaditalia/secp256k1-frost)           | 基于 libsecp256k1 的 FROST 实验实现。                                                      |

---

## 📘 选型建议

| 场景                          | 推荐库                                          |
| ----------------------------- | ----------------------------------------------- |
| ECDSA 链 (BTC / ETH)          | `tss-lib`, `threshold-lib`, `CGGMP21-Rust`      |
| Schnorr 链 (Taproot / Solana) | `FROST`, `multi-party-eddsa`, `secp256k1-frost` |
| 浏览器 / 前端                 | `blind-threshold-bls-wasm`                      |
| 高性能 / 嵌入式               | `multi-party-sig-cpp`                           |
| 教学 / 研究                   | `tinysig`, `py-ggmpc`, `protect`                |

---

## ⚠️ 安全与审计提醒

- 请核查各库的 **最近提交时间、审计报告** 与 **依赖安全性**。  
- 例如 BNB Chain `tss-lib` 曾涉及 [TSSHOCK 漏洞披露](https://verichains.io/tsshock/)。  
- 建议更新到最新 patch 并结合独立审计。  
- 对生产系统，应同时考虑：  
  - 网络交互安全（TLS / Noise Protocol）  
  - 签名份额恢复策略（resharing）  
  - 参与方认证与可追责性。  

---
